export const categories = [
  { id: "notebooks", name: "Notebooks", description: "Premium journals & notebooks", emoji: "📓" },
  { id: "pens", name: "Pens & Pencils", description: "Write with precision", emoji: "✒️" },
  { id: "planners", name: "Planners", description: "Organise your life beautifully", emoji: "📅" },
  { id: "desk", name: "Desk Accessories", description: "Elevate your workspace", emoji: "🖊️" },
  { id: "gifting", name: "Gift Sets", description: "Curated stationery gifts", emoji: "🎁" },
];

export const products = [
  {
    id: "1",
    name: "Linen Hardcover Journal",
    category: "notebooks",
    price: 849,
    originalPrice: 1099,
    description: "A beautifully crafted linen-bound hardcover journal with 192 pages of premium cream paper. Perfect for journaling, sketching, and note-taking.",
    colors: ["Sage Green", "Dusty Rose", "Slate Blue", "Warm Ivory"],
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop"],
    badge: "Bestseller",
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Weekly Desk Planner 2025",
    category: "planners",
    price: 649,
    originalPrice: null,
    description: "Stay organised in style with our undated weekly planner. Features a clean, minimal layout with space for goals, tasks, and reflections.",
    colors: ["Charcoal", "Blush Pink"],
    images: ["https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&auto=format&fit=crop"],
    badge: "New",
    inStock: true,
    rating: 4.6,
    reviews: 87,
  },
  {
    id: "3",
    name: "Brass Fountain Pen",
    category: "pens",
    price: 1299,
    originalPrice: 1599,
    description: "A timeless brass fountain pen with a smooth medium nib. Weighted perfectly for long writing sessions. Includes one ink cartridge.",
    colors: ["Raw Brass", "Matte Black"],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop"],
    badge: "Premium",
    inStock: true,
    rating: 4.9,
    reviews: 56,
  },
  {
    id: "4",
    name: "Kraft Sticky Note Set",
    category: "desk",
    price: 299,
    originalPrice: null,
    description: "Set of 200 kraft paper sticky notes in 4 sizes. Eco-friendly, recycled paper with strong adhesive.",
    colors: ["Natural Kraft"],
    images: ["https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.5,
    reviews: 203,
  },
  {
    id: "5",
    name: "Starter Gift Set",
    category: "gifting",
    price: 1799,
    originalPrice: 2200,
    description: "The perfect Klookins starter set — includes a linen journal, a set of fine-liners, and a mini planner. Gift-wrapped in our signature box.",
    colors: ["Sage Green", "Dusty Rose"],
    images: ["https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=600&auto=format&fit=crop"],
    badge: "Gift Ready",
    inStock: true,
    rating: 4.9,
    reviews: 41,
  },
  {
    id: "6",
    name: "Wooden Desk Organiser",
    category: "desk",
    price: 999,
    originalPrice: null,
    description: "Handcrafted from sustainable mango wood. Holds pens, scissors, sticky notes, and more. A beautiful addition to any desk.",
    colors: ["Natural Wood", "Dark Walnut"],
    images: ["https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop"],
    badge: "Handcrafted",
    inStock: true,
    rating: 4.7,
    reviews: 68,
  },
  {
    id: "7",
    name: "Pastel Fineliner Set",
    category: "pens",
    price: 499,
    originalPrice: 599,
    description: "Set of 12 pastel fineliners with 0.4mm tip. Fade-resistant, water-based ink. Great for bullet journaling and colour-coding.",
    colors: ["Pastel Set"],
    images: ["https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.6,
    reviews: 145,
  },
  {
    id: "8",
    name: "Softcover Dot Grid Notebook",
    category: "notebooks",
    price: 449,
    originalPrice: null,
    description: "Flexible softcover notebook with dot grid pages. Ideal for bullet journaling, sketching, and calligraphy practice.",
    colors: ["Terracotta", "Forest Green", "Navy"],
    images: ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.4,
    reviews: 92,
  },
];

export const featuredProducts = products.slice(0, 4);
