export const categories = [
  { id: "water-bottles", name: "Bottles", description: "Stay hydrated in style", emoji: "💧" },
];

export const products = [
  {
    id: "1",
    name: "Copper Water Bottle",
    category: "water-bottles",
    price: 699,
    originalPrice: 899,
    description: "Handcrafted pure copper water bottle — Ayurvedically recommended for storing drinking water. Holds 1 litre. Leakproof lid included.",
    colors: ["Hammered Copper", "Plain Copper"],
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop"],
    badge: "Bestseller",
    inStock: true,
    rating: 4.8,
    reviews: 211,
  },
  {
    id: "2",
    name: "Insulated Steel Bottle 1L",
    category: "water-bottles",
    price: 849,
    originalPrice: null,
    description: "Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12. Sweat-free and drop-resistant. 1 litre capacity.",
    colors: ["Matte Black", "Forest Green", "Blush Pink", "Slate Blue"],
    images: ["https://images.unsplash.com/photo-1625708458528-802ec79b1ed8?w=600&auto=format&fit=crop"],
    badge: "New",
    inStock: true,
    rating: 4.7,
    reviews: 143,
  },
  {
    id: "3",
    name: "Borosilicate Glass Bottle",
    category: "water-bottles",
    price: 599,
    originalPrice: 749,
    description: "Crystal-clear borosilicate glass bottle with a protective silicone sleeve. Dishwasher safe. 750ml. No metallic taste, ever.",
    colors: ["Clear", "Sage Sleeve", "Terracotta Sleeve"],
    images: ["https://images.unsplash.com/photo-1633354557121-98c12ac821bf?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.5,
    reviews: 89,
  },
  {
    id: "4",
    name: "Ceramic-Coated Steel Bottle",
    category: "water-bottles",
    price: 999,
    originalPrice: 1199,
    description: "Premium steel bottle with a smooth ceramic interior coating — zero metallic taste, easy to clean, and safe for all beverages including coffee and tea.",
    colors: ["Ivory White", "Sage Green", "Dusty Mauve", "Charcoal"],
    images: ["https://images.unsplash.com/photo-1589365278144-c9e705f843ba?w=600&auto=format&fit=crop"],
    badge: "Premium",
    inStock: true,
    rating: 4.8,
    reviews: 97,
  },
  {
    id: "5",
    name: "Wide Mouth Insulated Flask",
    category: "water-bottles",
    price: 1099,
    originalPrice: null,
    description: "Extra-wide mouth for easy filling, ice cubes, and cleaning. 500ml double-wall vacuum insulated stainless steel. Pairs with our straw and flip lids.",
    colors: ["Alpine White", "Midnight Black", "Ocean Blue", "Terracotta"],
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop"],
    badge: "New",
    inStock: true,
    rating: 4.6,
    reviews: 54,
  },
  {
    id: "6",
    name: "Bamboo & Steel Bottle",
    category: "water-bottles",
    price: 799,
    originalPrice: 999,
    description: "Sustainable stainless steel bottle with a natural bamboo lid and base ring. Double-walled for insulation. 500ml. Earthy, beautiful, and eco-conscious.",
    colors: ["Natural Bamboo", "Dark Bamboo"],
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&auto=format&fit=crop"],
    badge: "Eco",
    inStock: true,
    rating: 4.7,
    reviews: 76,
  },
  {
    id: "7",
    name: "Matte Steel Bottle 750ml",
    category: "water-bottles",
    price: 749,
    originalPrice: null,
    description: "Sleek matte powder-coated stainless steel. 750ml double-wall insulated. Sweat-proof, scratch-resistant, and minimalist.",
    colors: ["Frost White", "Smoke Grey", "Blush", "Sand Beige"],
    images: ["https://images.unsplash.com/photo-1585083969600-495ee7e3604b?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.5,
    reviews: 62,
  },
  {
    id: "8",
    name: "Stainless Sports Flask",
    category: "water-bottles",
    price: 649,
    originalPrice: 799,
    description: "Stainless steel sports flask with a one-touch flip spout and locking mechanism. 750ml double-wall insulated. Ideal for gym, cycling, and outdoor workouts.",
    colors: ["Electric Blue", "Olive Green", "Bright Orange", "Charcoal"],
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop"],
    badge: "Sale",
    inStock: true,
    rating: 4.4,
    reviews: 118,
  },
  {
    id: "9",
    name: "Kids Insulated Steel Bottle",
    category: "water-bottles",
    price: 549,
    originalPrice: null,
    description: "Compact 360ml stainless steel bottle designed for little hands. Double-wall insulated and drop-tested. Easy-open flip lid with a lock mechanism.",
    colors: ["Sky Blue", "Sunshine Yellow", "Coral Pink", "Mint Green"],
    images: ["https://images.unsplash.com/photo-1664714628878-9d2aa898b9e3?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.8,
    reviews: 203,
  },
  {
    id: "10",
    name: "Tall Slim Steel Bottle 500ml",
    category: "water-bottles",
    price: 699,
    originalPrice: null,
    description: "Slim stainless steel profile that fits any bag pocket or cup holder. 500ml double-wall vacuum insulated. Lightweight at just 220g.",
    colors: ["Pearl White", "Jet Black", "Rose Gold", "Cobalt Blue"],
    images: ["https://images.unsplash.com/photo-1589365278144-c9e705f843ba?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.6,
    reviews: 88,
  },
];

export const featuredProducts = products.filter((p) =>
  ["1", "2", "4", "6"].includes(p.id)
);

export const builderBases = [
  {
    id: "360ml-steel",
    name: "360ml Steel",
    material: "Stainless Steel",
    size: "360ml",
    price: 399,
    colors: ["Chalk White", "Midnight Black", "Poppy Red", "Sky Blue", "Mint Green"],
    image: "https://images.unsplash.com/photo-1664714628878-9d2aa898b9e3?w=400&auto=format&fit=crop",
  },
  {
    id: "480ml-steel",
    name: "480ml Steel",
    material: "Stainless Steel",
    size: "480ml",
    price: 499,
    colors: ["Chalk White", "Forest Green", "Navy Blue", "Dusty Rose", "Terracotta"],
    image: "https://images.unsplash.com/photo-1625708458528-802ec79b1ed8?w=400&auto=format&fit=crop",
  },
  {
    id: "750ml-steel",
    name: "750ml Steel",
    material: "Stainless Steel",
    size: "750ml",
    price: 599,
    colors: ["Slate Blue", "Smoke Grey", "Blush Pink", "Sand Beige", "Olive Green"],
    image: "https://images.unsplash.com/photo-1585083969600-495ee7e3604b?w=400&auto=format&fit=crop",
  },
  {
    id: "1l-steel",
    name: "1L Steel",
    material: "Stainless Steel",
    size: "1L",
    price: 699,
    colors: ["Matte Black", "Alpine White", "Ocean Blue", "Sage Green", "Charcoal"],
    image: "https://images.unsplash.com/photo-1544003484-3cd181d17917?w=400&auto=format&fit=crop",
  },
  {
    id: "750ml-glass",
    name: "750ml Glass",
    material: "Borosilicate Glass",
    size: "750ml",
    price: 549,
    colors: ["Clear + Sage", "Clear + Terracotta", "Clear + Navy", "Clear + Blush"],
    image: "https://images.unsplash.com/photo-1633354557121-98c12ac821bf?w=400&auto=format&fit=crop",
  },
  {
    id: "1l-copper",
    name: "1L Copper",
    material: "Pure Copper",
    size: "1L",
    price: 649,
    colors: ["Hammered Copper", "Plain Copper"],
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&auto=format&fit=crop",
  },
  {
    id: "500ml-ceramic",
    name: "500ml Ceramic-Coated",
    material: "Ceramic-Coated Steel",
    size: "500ml",
    price: 649,
    colors: ["Ivory White", "Sage Green", "Dusty Mauve", "Warm Charcoal"],
    image: "https://images.unsplash.com/photo-1589365278144-c9e705f843ba?w=400&auto=format&fit=crop",
  },
  {
    id: "500ml-bamboo",
    name: "500ml Bamboo & Steel",
    material: "Bamboo & Steel",
    size: "500ml",
    price: 599,
    colors: ["Natural Bamboo", "Dark Bamboo"],
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&auto=format&fit=crop",
  },
];

export const builderLids = [
  {
    id: "screw",
    name: "Screw Lid",
    description: "Classic leakproof silicone screw top. Best for everyday carry.",
    price: 149,
  },
  {
    id: "flip",
    name: "Flip Lid",
    description: "One-touch flip-open cap with lock. Great for on-the-go.",
    price: 199,
  },
  {
    id: "straw",
    name: "Straw Lid",
    description: "Silicone lid with stainless steel straw included. Sip without tilting.",
    price: 249,
  },
  {
    id: "sports",
    name: "Sports Lid",
    description: "Wide-mouth pull-up spout. Fast flow for workouts.",
    price: 199,
  },
];

export const builderAccessories = [
  {
    id: "bumper-small",
    name: "Bumper & Tab Set (Small)",
    description: "Silicone base bumper + lid tab for 360ml bottles. Protects surfaces.",
    price: 199,
    sizeFit: "360ml",
  },
  {
    id: "bumper-large",
    name: "Bumper & Tab Set (Large)",
    description: "Silicone base bumper + lid tab for 480ml, 750ml & 1L bottles.",
    price: 199,
    sizeFit: "480ml+",
  },
  {
    id: "sleeve",
    name: "Bottle Sleeve",
    description: "Neoprene grip sleeve for extra insulation and grip.",
    price: 199,
    sizeFit: "all",
  },
  {
    id: "strap",
    name: "Carry Strap",
    description: "Adjustable paracord strap. Clips to lid or base ring.",
    price: 149,
    sizeFit: "all",
  },
  {
    id: "straw-set",
    name: "Spare Straw Set",
    description: "2 stainless steel straws + cleaning brush.",
    price: 149,
    sizeFit: "all",
  },
];

// Combinations shown in the animated homepage preview
export const builderCombinations = [
  {
    label: "The Everyday",
    base: { name: "480ml Steel", color: "Forest Green", material: "Stainless Steel", price: 499 },
    lid: { name: "Flip Lid", price: 199 },
    accessory: { name: "Carry Strap", price: 149 },
    image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&auto=format&fit=crop",
    accentColor: "bg-emerald-500",
  },
  {
    label: "The Heritage",
    base: { name: "1L Copper", color: "Hammered Copper", material: "Pure Copper", price: 649 },
    lid: { name: "Screw Lid", price: 149 },
    accessory: { name: "Bumper & Tab Set", price: 199 },
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop",
    accentColor: "bg-amber-600",
  },
  {
    label: "The Purist",
    base: { name: "750ml Glass", color: "Clear + Sage", material: "Borosilicate Glass", price: 549 },
    lid: { name: "Straw Lid", price: 249 },
    accessory: { name: "Bottle Sleeve", price: 199 },
    image: "https://images.unsplash.com/photo-1633354557121-98c12ac821bf?w=600&auto=format&fit=crop",
    accentColor: "bg-sage-500",
  },
  {
    label: "The Minimalist",
    base: { name: "500ml Ceramic-Coated", color: "Ivory White", material: "Ceramic-Coated Steel", price: 649 },
    lid: { name: "Flip Lid", price: 199 },
    accessory: { name: "Spare Straw Set", price: 149 },
    image: "https://images.unsplash.com/photo-1589365278144-c9e705f843ba?w=600&auto=format&fit=crop",
    accentColor: "bg-stone-300",
  },
  {
    label: "The Naturalist",
    base: { name: "500ml Bamboo & Steel", color: "Natural Bamboo", material: "Bamboo & Steel", price: 599 },
    lid: { name: "Screw Lid", price: 149 },
    accessory: { name: "Carry Strap", price: 149 },
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&auto=format&fit=crop",
    accentColor: "bg-yellow-700",
  },
];
