export const categories = [
  { id: "notebooks", name: "Notebooks", description: "Premium journals & notebooks", emoji: "📓" },
  { id: "pens", name: "Pens & Pencils", description: "Write with precision", emoji: "✒️" },
  { id: "planners", name: "Planners", description: "Organise your life beautifully", emoji: "📅" },
  { id: "sticky-notes", name: "Sticky Notes", description: "Colour-coded & fun", emoji: "📝" },
  { id: "desk", name: "Desk Accessories", description: "Elevate your workspace", emoji: "🖊️" },
  { id: "water-bottles", name: "Water Bottles", description: "Stay hydrated in style", emoji: "💧" },
  { id: "mugs", name: "Coffee & Mugs", description: "Your favourite brew, elevated", emoji: "☕" },
  { id: "lunch-boxes", name: "Lunch Boxes", description: "Meal prep made beautiful", emoji: "🍱" },
  { id: "umbrellas", name: "Umbrellas", description: "Beat the rain in style", emoji: "☂️" },
  { id: "backpacks", name: "Backpacks", description: "Carry everything beautifully", emoji: "🎒" },
  { id: "gifting", name: "Gift Sets", description: "Curated stationery gifts", emoji: "🎁" },
];

export const products = [
  // ── Stationery ──────────────────────────────────────────────────────────────
  {
    id: "1",
    name: "Linen Hardcover Journal",
    category: "notebooks",
    price: 849,
    originalPrice: 1099,
    description: "A beautifully crafted linen-bound hardcover journal with 192 pages of premium cream paper. Perfect for journaling, sketching, and note-taking.",
    colors: ["Sage Green", "Dusty Rose", "Slate Blue", "Warm Ivory"],
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop"],
    badge: "Bestseller",
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Weekly Desk Planner 2025",
    category: "planners",
    price: 649,
    originalPrice: null,
    description: "Stay organised in style with our undated weekly planner. Features a clean, minimal layout with space for goals, tasks, and reflections.",
    colors: ["Charcoal", "Blush Pink"],
    images: ["https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&auto=format&fit=crop"],
    badge: "New",
    inStock: true,
    rating: 4.6,
    reviews: 87,
  },
  {
    id: "3",
    name: "Brass Fountain Pen",
    category: "pens",
    price: 1299,
    originalPrice: 1599,
    description: "A timeless brass fountain pen with a smooth medium nib. Weighted perfectly for long writing sessions. Includes one ink cartridge.",
    colors: ["Raw Brass", "Matte Black"],
    images: ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop"],
    badge: "Premium",
    inStock: true,
    rating: 4.9,
    reviews: 56,
  },
  {
    id: "4",
    name: "Kraft Sticky Note Set",
    category: "sticky-notes",
    price: 299,
    originalPrice: null,
    description: "Set of 200 kraft paper sticky notes in 4 sizes. Eco-friendly, recycled paper with strong adhesive that won't damage your pages.",
    colors: ["Natural Kraft"],
    images: ["https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.5,
    reviews: 203,
  },
  {
    id: "5",
    name: "Starter Gift Set",
    category: "gifting",
    price: 1799,
    originalPrice: 2200,
    description: "The perfect Klookins starter set — includes a linen journal, a set of fine-liners, and a mini planner. Gift-wrapped in our signature box.",
    colors: ["Sage Green", "Dusty Rose"],
    images: ["https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=600&auto=format&fit=crop"],
    badge: "Gift Ready",
    inStock: true,
    rating: 4.9,
    reviews: 41,
  },
  {
    id: "6",
    name: "Wooden Desk Organiser",
    category: "desk",
    price: 999,
    originalPrice: null,
    description: "Handcrafted from sustainable mango wood. Holds pens, scissors, sticky notes, and more. A beautiful addition to any desk.",
    colors: ["Natural Wood", "Dark Walnut"],
    images: ["https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop"],
    badge: "Handcrafted",
    inStock: true,
    rating: 4.7,
    reviews: 68,
  },
  {
    id: "7",
    name: "Pastel Fineliner Set",
    category: "pens",
    price: 499,
    originalPrice: 599,
    description: "Set of 12 pastel fineliners with 0.4mm tip. Fade-resistant, water-based ink. Great for bullet journaling and colour-coding.",
    colors: ["Pastel Set"],
    images: ["https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.6,
    reviews: 145,
  },
  {
    id: "8",
    name: "Softcover Dot Grid Notebook",
    category: "notebooks",
    price: 449,
    originalPrice: null,
    description: "Flexible softcover notebook with dot grid pages. Ideal for bullet journaling, sketching, and calligraphy practice.",
    colors: ["Terracotta", "Forest Green", "Navy"],
    images: ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.4,
    reviews: 92,
  },

  // ── Sticky Notes ─────────────────────────────────────────────────────────────
  {
    id: "9",
    name: "Pastel Sticky Note Collection",
    category: "sticky-notes",
    price: 349,
    originalPrice: null,
    description: "Six colours, three sizes, 300 sheets total. Our bestselling pastel sticky notes are perfect for desks, planners, and books. Won't leave residue.",
    colors: ["Pastel Set"],
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop"],
    badge: "Bestseller",
    inStock: true,
    rating: 4.7,
    reviews: 318,
  },
  {
    id: "10",
    name: "Large Sticky Note Pad A5",
    category: "sticky-notes",
    price: 199,
    originalPrice: null,
    description: "50 large A5 sticky notes — perfect for meeting notes, to-do lists, or mood boards. Strong adhesive keeps them in place all day.",
    colors: ["Pastel Yellow", "Pastel Blue", "Pastel Pink"],
    images: ["https://images.unsplash.com/photo-1603484477859-abe6a73f9366?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.3,
    reviews: 74,
  },
  {
    id: "11",
    name: "Neon Sticky Note Pack",
    category: "sticky-notes",
    price: 249,
    originalPrice: 299,
    description: "High-visibility neon sticky notes in 5 fluorescent shades. Impossible to miss. Great for urgent reminders and colour-coded systems.",
    colors: ["Neon Set"],
    images: ["https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600&auto=format&fit=crop"],
    badge: "Sale",
    inStock: true,
    rating: 4.4,
    reviews: 56,
  },

  // ── Water Bottles ────────────────────────────────────────────────────────────
  {
    id: "12",
    name: "Copper Water Bottle",
    category: "water-bottles",
    price: 699,
    originalPrice: 899,
    description: "Handcrafted pure copper water bottle — Ayurvedically recommended for storing drinking water. Holds 1 litre. Leakproof lid included.",
    colors: ["Hammered Copper", "Plain Copper"],
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop"],
    badge: "Bestseller",
    inStock: true,
    rating: 4.8,
    reviews: 211,
  },
  {
    id: "13",
    name: "Insulated Steel Bottle 1L",
    category: "water-bottles",
    price: 849,
    originalPrice: null,
    description: "Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12. Sweat-free, BPA-free, and drop-resistant. 1 litre capacity.",
    colors: ["Matte Black", "Forest Green", "Blush Pink", "Slate Blue"],
    images: ["https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&auto=format&fit=crop"],
    badge: "New",
    inStock: true,
    rating: 4.7,
    reviews: 143,
  },
  {
    id: "14",
    name: "Borosilicate Glass Bottle",
    category: "water-bottles",
    price: 599,
    originalPrice: 749,
    description: "Crystal-clear borosilicate glass bottle with a protective silicone sleeve. Dishwasher safe. 750ml. No plastic taste, ever.",
    colors: ["Clear", "Sage Sleeve", "Terracotta Sleeve"],
    images: ["https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.5,
    reviews: 89,
  },

  // ── Coffee & Mugs ────────────────────────────────────────────────────────────
  {
    id: "15",
    name: "Handmade Ceramic Mug",
    category: "mugs",
    price: 449,
    originalPrice: null,
    description: "Each mug is wheel-thrown by Indian artisans — no two are exactly alike. Holds 350ml. Microwave and dishwasher safe. Perfect for your morning ritual.",
    colors: ["Sage Green", "Speckled White", "Terracotta", "Midnight Blue"],
    images: ["https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&auto=format&fit=crop"],
    badge: "Handcrafted",
    inStock: true,
    rating: 4.9,
    reviews: 176,
  },
  {
    id: "16",
    name: "Double-Wall Glass Mug",
    category: "mugs",
    price: 599,
    originalPrice: 699,
    description: "Borosilicate glass with a double-wall for insulation — keeps your drink hot while staying cool to the touch. 300ml. A visual treat to watch.",
    colors: ["Clear"],
    images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.6,
    reviews: 94,
  },
  {
    id: "17",
    name: "Travel Tumbler with Lid",
    category: "mugs",
    price: 799,
    originalPrice: null,
    description: "18/8 stainless steel travel tumbler with a spill-proof sliding lid. Keeps coffee hot for 6 hours. 450ml. Fits most car cup holders.",
    colors: ["Charcoal", "Rose Gold", "Ivory White"],
    images: ["https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop"],
    badge: "New",
    inStock: true,
    rating: 4.7,
    reviews: 62,
  },

  // ── Lunch Boxes ──────────────────────────────────────────────────────────────
  {
    id: "18",
    name: "Stainless Steel Bento Box",
    category: "lunch-boxes",
    price: 899,
    originalPrice: null,
    description: "Food-grade 18/8 stainless steel bento box with three leakproof compartments. Keeps portions separate, odour-free, and easy to clean.",
    colors: ["Silver", "Matte Black"],
    images: ["https://images.unsplash.com/photo-1598103442097-8b74394b95c5?w=600&auto=format&fit=crop"],
    badge: "Bestseller",
    inStock: true,
    rating: 4.8,
    reviews: 134,
  },
  {
    id: "19",
    name: "3-Tier Insulated Tiffin Box",
    category: "lunch-boxes",
    price: 1099,
    originalPrice: 1299,
    description: "Classic 3-tier stainless steel tiffin with an insulated carry bag. Keeps food hot for up to 4 hours. Each tier holds 400ml. Stackable and leakproof.",
    colors: ["Steel Silver"],
    images: ["https://images.unsplash.com/photo-1611599537845-1c7aca0091c0?w=600&auto=format&fit=crop"],
    badge: "Sale",
    inStock: true,
    rating: 4.6,
    reviews: 87,
  },
  {
    id: "20",
    name: "Wheat Straw Lunch Box",
    category: "lunch-boxes",
    price: 449,
    originalPrice: null,
    description: "Eco-friendly lunch box made from natural wheat straw fibre — lightweight, BPA-free, and microwave safe. Two-compartment design with a snap-lock lid.",
    colors: ["Sage Green", "Dusty Pink", "Sky Blue"],
    images: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop"],
    badge: "Eco",
    inStock: true,
    rating: 4.4,
    reviews: 58,
  },

  // ── Umbrellas ────────────────────────────────────────────────────────────────
  {
    id: "21",
    name: "Compact Auto Umbrella",
    category: "umbrellas",
    price: 699,
    originalPrice: 899,
    description: "One-touch auto open and close. Windproof fibreglass ribs, UV-protective coating. Fits in any bag. Perfect for Indian monsoons.",
    colors: ["Classic Black", "Navy Blue", "Forest Green"],
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop"],
    badge: "Bestseller",
    inStock: true,
    rating: 4.7,
    reviews: 209,
  },
  {
    id: "22",
    name: "Windproof Inverted Umbrella",
    category: "umbrellas",
    price: 999,
    originalPrice: null,
    description: "Inverted design means no water drips on you when closing. Double-layer canopy with 10 reinforced ribs. Stands on its own when open.",
    colors: ["Midnight Black", "Earthy Brown", "Charcoal Grey"],
    images: ["https://images.unsplash.com/photo-1538374432745-a1f2e13db1e1?w=600&auto=format&fit=crop"],
    badge: "New",
    inStock: true,
    rating: 4.8,
    reviews: 73,
  },
  {
    id: "23",
    name: "Transparent Bubble Umbrella",
    category: "umbrellas",
    price: 799,
    originalPrice: null,
    description: "Full-dome transparent canopy gives you complete visibility in the rain. Sturdy fibreglass frame with a comfortable wooden-look handle.",
    colors: ["Clear", "Pink Trim", "Black Trim"],
    images: ["https://images.unsplash.com/photo-1501621667575-af81f1f0bacc?w=600&auto=format&fit=crop"],
    badge: null,
    inStock: true,
    rating: 4.5,
    reviews: 44,
  },

  // ── Backpacks ────────────────────────────────────────────────────────────────
  {
    id: "24",
    name: "Canvas Laptop Backpack 15\"",
    category: "backpacks",
    price: 2499,
    originalPrice: 2999,
    description: "Heavy-duty waxed canvas backpack with a padded 15\" laptop sleeve, organiser pocket, and leather accents. Water-resistant. Built to last years.",
    colors: ["Khaki", "Navy", "Charcoal"],
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop"],
    badge: "Premium",
    inStock: true,
    rating: 4.9,
    reviews: 97,
  },
  {
    id: "25",
    name: "Mini Everyday Daypack",
    category: "backpacks",
    price: 1499,
    originalPrice: null,
    description: "Compact 15L daypack for commutes and weekend trips. Lightweight ripstop fabric, multiple pockets, and a comfortable back panel. Fits a 13\" laptop.",
    colors: ["Sage Green", "Rust Orange", "Stone Grey"],
    images: ["https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&auto=format&fit=crop"],
    badge: "New",
    inStock: true,
    rating: 4.6,
    reviews: 53,
  },
  {
    id: "26",
    name: "Rolltop Commuter Pack 20L",
    category: "backpacks",
    price: 1999,
    originalPrice: 2499,
    description: "Weatherproof rolltop closure keeps your gear dry. 20L capacity with a quick-access front pocket and a laptop sleeve. Great for daily commutes.",
    colors: ["Matte Black", "Olive Green"],
    images: ["https://images.unsplash.com/photo-1581605405669-fcdf81165afa?w=600&auto=format&fit=crop"],
    badge: "Sale",
    inStock: true,
    rating: 4.7,
    reviews: 68,
  },
];

export const featuredProducts = products.filter((p) =>
  ["1", "3", "12", "15", "21", "24", "5", "18"].includes(p.id)
).slice(0, 4);
